<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;netstandard2.0</TargetFrameworks>
		<LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Nito.Collections.Deque" Version="1.2.1" />
    <PackageReference Include="Serilog" Version="3.1.1" />
    <PackageReference Include="Sodium.Core" Version="1.4.1" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <None Update="JSON\PacketDefinitions\LoginPacketGenerator.log">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>LoginPacketGenerator.tt</DependentUpon>
    </None>
    <None Update="JSON\PacketDefinitions\LoginPacketGenerator.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>LoginPacketGenerator.log</LastGenOutput>
    </None>
  </ItemGroup>

	<Target Name="CopyToUnity" AfterTargets="Build" Condition="'$(TargetFramework)' == 'netstandard2.0'">
		<Copy
			SourceFiles="$(OutputPath)LibPegasus.dll"
			DestinationFolder="D:\Coding\Eclipse_Client\Eclipse\Assets\Plugins"
			SkipUnchangedFiles="true" />
	</Target>

</Project>
