// <auto-generated>
//    Generated from Login.yaml — do NOT edit manually.
// </auto-generated>
namespace LibPegasus.Enums
{
	public enum OpcodeLogin
	{
		CHECKVERSION = 1,
		AUTHACCOUNT = 2,
		SERVERSTATE = 3,
		CONNECTSERVER = 4,
		VERIFYLINKS = 5,
	}
}
