// <auto-generated>
//    Generated from World.yaml — do NOT edit manually.
// </auto-generated>
namespace LibPegasus.Enums
{
	public enum OpcodeWorld : UInt16
	{
		CONNECTSERVER = 1,
		LINKSUCCESS = 2,
		LINKBACK = 3,
	}
}
