// <auto-generated>
//    Generated from World.json — do NOT edit manually.
// </auto-generated>
#nullable enable
using LibPegasus.Enums;
using LibPegasus.Packets;
using Nito.Collections;
using System;
using System.Collections.Generic;

namespace LibPegasus.Packets.World.C2S
{
	public class REQ_DummyPacket<ClientClass> : Packet<ClientClass>
	{
		private byte[]? _req;

		public static Action<ClientClass, byte[]>? DummyPacketHandler;

		public REQ_DummyPacket(Queue<byte> data) : base((UInt16)OpcodeWorld.DUMMYPACKET, data) { }

		public override bool ReadPayload(Queue<Action<ClientClass>> actions)
		{
			try
			{
				_req = PacketReader.ReadArray(_data);
			}
			catch (IndexOutOfRangeException) { return false; }

			if (DummyPacketHandler == null)
				throw new InvalidOperationException("Handler not assigned");

			actions.Enqueue((x) => DummyPacketHandler?.Invoke(x, _req));
			return true;
		}

		public REQ_DummyPacket(byte[] req) : base((UInt16)OpcodeWorld.DUMMYPACKET)
		{
			_req = req;
		}

		public override void WritePayload(Deque<byte> data)
		{
			PacketWriter.WriteArray(data, _req);
		}
	}
}
