// <auto-generated>
//    Generated from World.yaml — do NOT edit manually.
// </auto-generated>
#nullable enable
using Google.Protobuf;
using LibPegasus.Enums;
using LibPegasus.Packets;
using Nito.Collections;
using System;
using System.Buffers;
using System.Collections.Generic;

namespace LibPegasus.Packets.World.C2S
{
	public class REQ_ConnectServer<ClientClass> : Packet<ClientClass>
	{
		public LibPegasus.Protobuf.World.ConnectServerReq Body { get; private set; }

		public static Action<ClientClass, LibPegasus.Protobuf.World.ConnectServerReq>? ConnectServerHandler;

		public REQ_ConnectServer(Queue<byte> data) : base((UInt16)OpcodeWorld.CONNECTSERVER, data)
		{
			Body = new LibPegasus.Protobuf.World.ConnectServerReq();
		}

		public REQ_ConnectServer(LibPegasus.Protobuf.World.ConnectServerReq body) : base((UInt16)OpcodeWorld.CONNECTSERVER)
		{
			Body = body ?? throw new ArgumentNullException(nameof(body));
		}

		public override bool ReadPayload(Queue<Action<ClientClass>> actions)
		{
			int payloadSize = _data.Count;
			if (payloadSize == 0) return false;

			byte[] buffer = ArrayPool<byte>.Shared.Rent(payloadSize);
			try
			{
				Span<byte> span = buffer.AsSpan(0, payloadSize);
				PacketReader.ReadSpan(_data, span);
				Body = LibPegasus.Protobuf.World.ConnectServerReq.Parser.ParseFrom(span);
			}
			catch (InvalidProtocolBufferException)
			{
				return false;
			}
			finally
			{
				ArrayPool<byte>.Shared.Return(buffer, clearArray: false);
			}

			if (ConnectServerHandler == null)
				throw new InvalidOperationException("Handler not assigned");

			actions.Enqueue((client) => ConnectServerHandler?.Invoke(client, Body));
			return true;
		}

		public override int WritePayload(Deque<byte> data)
		{
			if (Body == null) return 0;

			int size = Body.CalculateSize();
			if (size == 0) return 0;

			byte[] buffer = ArrayPool<byte>.Shared.Rent(size);
			try
			{
				Span<byte> span = buffer.AsSpan(0, size);
				Body.WriteTo(span);
				PacketWriter.WriteArray(data, span);
			}
			finally
			{
				ArrayPool<byte>.Shared.Return(buffer, clearArray: false);
			}
			return size;
		}
	}
}
