// <auto-generated>
//    Generated from World.yaml — do NOT edit manually.
// </auto-generated>
#nullable enable
using Google.Protobuf;
using LibPegasus.Enums;
using LibPegasus.Packets;
using Nito.Collections;
using System;
using System.Collections.Generic;

namespace LibPegasus.Packets.World.C2S
{
	public class REQ_ConnectServer<ClientClass> : Packet<ClientClass>
	{
		public LibPegasus.Protobuf.World.ConnectServerReq Body { get; private set; }

		public static Action<ClientClass, LibPegasus.Protobuf.World.ConnectServerReq>? ConnectServerHandler;

		public REQ_ConnectServer(Queue<byte> data) : base((UInt16)OpcodeWorld.CONNECTSERVER, data)
		{
			Body = new LibPegasus.Protobuf.World.ConnectServerReq();
		}

		public REQ_ConnectServer(LibPegasus.Protobuf.World.ConnectServerReq body) : base((UInt16)OpcodeWorld.CONNECTSERVER)
		{
			Body = body ?? throw new ArgumentNullException(nameof(body));
		}

		public override bool ReadPayload(Queue<Action<ClientClass>> actions)
		{
			try
			{
				byte[] payloadBytes = PacketReader.ReadArray(_data);
				Body = LibPegasus.Protobuf.World.ConnectServerReq.Parser.ParseFrom(payloadBytes);
			}
			catch (Exception)
			{
				return false;
			}

			if (ConnectServerHandler == null)
				throw new InvalidOperationException("Handler not assigned");

			actions.Enqueue((client) => ConnectServerHandler?.Invoke(client, Body));
			return true;
		}

		public override void WritePayload(Deque<byte> data)
		{
			byte[] payloadBytes = Body.ToByteArray();
			PacketWriter.WriteArray(data, payloadBytes);
		}
	}
}
