// <auto-generated>
//   Generated by Packets.tt — do NOT edit manually.
// </auto-generated>
namespace LibPegasus.Packets.World
{
	public static class WorldPacketVersion
	{
		public const int Revision = 6;
	}
}
