using System;
using System.Collections.Generic;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;

if (args.Length == 0)
{
	Console.WriteLine("Usage: PacketGenerator <path-to-yaml>");
	return;
}

string yamlPath = Path.GetFullPath(args[0]);
if (!File.Exists(yamlPath))
{
	Console.WriteLine($"Error: File not found: {yamlPath}");
	return;
}

string yamlDir = Path.GetDirectoryName(yamlPath)!;
string rawText = File.ReadAllText(yamlPath);
string yamlText = rawText
	.Replace('\u00A0', ' ')
	.Replace("\r\n", "\n");

// ── Deserialize YAML Config ──────────────────────────────────────────────────
var deserializer = new DeserializerBuilder()
	.WithNamingConvention(CamelCaseNamingConvention.Instance)
	.IgnoreUnmatchedProperties()
	.Build();

var config = deserializer.Deserialize<PacketConfig>(yamlText);

string namespaceName = config.Namespace;
string opcodeEnum = config.OpcodeEnum;
string outputPath = config.OutputPath;

string targetOutputDir = Path.GetFullPath(Path.Combine(yamlDir, outputPath));
Directory.CreateDirectory(targetOutputDir);

// ── Revision Check ──────────────────────────────────────────────────────────
string yamlFileName = Path.GetFileNameWithoutExtension(yamlPath);
string revisionPath = Path.Combine(yamlDir, $"{yamlFileName}Version.json");

int revision = 0;
string storedHash = "";

if (File.Exists(revisionPath))
{
	try
	{
		using var doc = System.Text.Json.JsonDocument.Parse(File.ReadAllText(revisionPath));
		var revRoot = doc.RootElement;
		revision = revRoot.GetProperty("revision").GetInt32();
		storedHash = revRoot.TryGetProperty("hash", out var h) ? h.GetString() ?? "" : "";
	}
	catch { }
}

byte[] hashBytes = MD5.HashData(Encoding.UTF8.GetBytes(yamlText));
string currentHash = Convert.ToHexString(hashBytes).ToLowerInvariant();

if (currentHash != storedHash)
{
	revision++;
	string revisionJson = System.Text.Json.JsonSerializer.Serialize(
		new { revision, hash = currentHash },
		new System.Text.Json.JsonSerializerOptions { WriteIndented = true }
	);
	WriteFileIfChanged(revisionPath, revisionJson);
}

// ── Emit Revision File ───────────────────────────────────────────────────────
var revSb = new StringBuilder();
revSb.AppendLine("// <auto-generated>");
revSb.AppendLine($"//    Generated from {Path.GetFileName(yamlPath)} — do NOT edit manually.");
revSb.AppendLine("// </auto-generated>");
revSb.AppendLine($"namespace {namespaceName}");
revSb.AppendLine("{");
revSb.AppendLine($"\tpublic static class {yamlFileName}PacketVersion");
revSb.AppendLine("\t{");
revSb.AppendLine($"\t\tpublic const int Revision = {revision};");
revSb.AppendLine("\t}");
revSb.AppendLine("}");

WriteFileIfChanged(Path.Combine(targetOutputDir, $"{yamlFileName}PacketVersion.cs"), revSb.ToString());

// ── Generate Packets ────────────────────────────────────────────────────────
int filesWritten = 1;

foreach (var (packetName, packetSpec) in config.Packets)
{
	string opcode = packetName.ToUpperInvariant();

	foreach (var (dirKey, dirSpec) in packetSpec)
	{
		bool isC2S = dirKey.Equals("C2S", StringComparison.OrdinalIgnoreCase);

		string prefix = isC2S ? "REQ" : (!string.IsNullOrEmpty(dirSpec.Prefix) ? dirSpec.Prefix : "RSP");
		string protoType = dirSpec.Proto ?? throw new InvalidOperationException($"Packet '{packetName}' [{dirKey}] is missing 'proto' binding.");

		string className = $"{prefix}_{packetName}";
		string handlerName = $"{packetName}Handler";
		string nsDir = isC2S ? "C2S" : "S2C";
		string fullNs = $"{namespaceName}.{nsDir}";

		var sb = new StringBuilder();
		sb.AppendLine("// <auto-generated>");
		sb.AppendLine($"//    Generated from {Path.GetFileName(yamlPath)} — do NOT edit manually.");
		sb.AppendLine("// </auto-generated>");
		sb.AppendLine("#nullable enable");
		sb.AppendLine("using Google.Protobuf;");
		sb.AppendLine("using LibPegasus.Enums;");
		sb.AppendLine("using LibPegasus.Packets;");
		sb.AppendLine("using Nito.Collections;");
		sb.AppendLine("using System;");
		sb.AppendLine("using System.Buffers;");
		sb.AppendLine("using System.Collections.Generic;");
		sb.AppendLine();
		sb.AppendLine($"namespace {fullNs}");
		sb.AppendLine("{");
		sb.AppendLine($"\tpublic class {className}<ClientClass> : Packet<ClientClass>");
		sb.AppendLine("\t{");

		// Body Property
		sb.AppendLine($"\t\tpublic {protoType} Body {{ {(isC2S ? "get; private set;" : "get; private set;")} }}");
		sb.AppendLine();

		// Handler Definition
		sb.AppendLine($"\t\tpublic static Action<ClientClass, {protoType}>? {handlerName};");
		sb.AppendLine();

		// Inbound / Queue Constructor
		sb.AppendLine($"\t\tpublic {className}(byte[] data) : base((UInt16){opcodeEnum}.{opcode}, data)");
		sb.AppendLine("\t\t{");
		sb.AppendLine($"\t\t\tBody = new {protoType}();");
		sb.AppendLine("\t\t}");
		sb.AppendLine();

		// Outbound / Body Constructor
		sb.AppendLine($"\t\tpublic {className}({protoType} body) : base((UInt16){opcodeEnum}.{opcode})");
		sb.AppendLine("\t\t{");
		sb.AppendLine("\t\t\tBody = body ?? throw new ArgumentNullException(nameof(body));");
		sb.AppendLine("\t\t}");
		sb.AppendLine();

		// ReadPayload Method
		sb.AppendLine("\t\tpublic override bool ReadPayload(Queue<Action<ClientClass>> actions)");
		sb.AppendLine("\t\t{");
		sb.AppendLine("\t\t\tif (_data == null)");
		sb.AppendLine("\t\t\t\tthrow new NullReferenceException(\"null _data\");");
		sb.AppendLine();
		sb.AppendLine("\t\t\tif (_data.Length < HEADER_SIZE)");
		sb.AppendLine("\t\t\t\treturn false;");
		sb.AppendLine();
		sb.AppendLine("\t\t\tReadOnlySpan<byte> span = _data.AsSpan(HEADER_SIZE);");
		sb.AppendLine("\t\t\tif (span.IsEmpty)");
		sb.AppendLine("\t\t\t\treturn true;");
		sb.AppendLine();
		sb.AppendLine("\t\t\ttry");
		sb.AppendLine("\t\t\t{");
		sb.AppendLine($"\t\t\t\tBody = {protoType}.Parser.ParseFrom(span);");
		sb.AppendLine("\t\t\t}");
		sb.AppendLine("\t\t\tcatch (InvalidProtocolBufferException ex)");
		sb.AppendLine("\t\t\t{");
		sb.AppendLine("\t\t\t\tSerilog.Log.Debug($\"{ex}\");");
		sb.AppendLine("\t\t\t\treturn false;");
		sb.AppendLine("\t\t\t}");
		sb.AppendLine();
		sb.AppendLine($"\t\t\tif ({handlerName} == null)");
		sb.AppendLine(isC2S ? "\t\t\t\tthrow new InvalidOperationException(\"Handler not assigned\");" : "\t\t\t\treturn false;");
		sb.AppendLine();
		sb.AppendLine($"\t\t\tactions.Enqueue((client) => {handlerName}?.Invoke(client, Body));");
		sb.AppendLine("\t\t\treturn true;");
		sb.AppendLine("\t\t}");
		sb.AppendLine();


		// WritePayload Method
		sb.AppendLine("\t\tpublic override byte[] WritePayload()");
		sb.AppendLine("\t\t{");
		sb.AppendLine("\t\t\tif (Body == null)");
		sb.AppendLine("\t\t\t\treturn new byte[HEADER_SIZE];");
		sb.AppendLine();
		sb.AppendLine("\t\t\tint size = Body.CalculateSize();");
		sb.AppendLine("\t\t\tbyte[] output = new byte[HEADER_SIZE + size];");
		sb.AppendLine();
		sb.AppendLine("\t\t\tif (size > 0)");
		sb.AppendLine("\t\t\t{");
		sb.AppendLine("\t\t\t\tSpan<byte> span = output.AsSpan(HEADER_SIZE, size);");
		sb.AppendLine("\t\t\t\tBody.WriteTo(span);");
		sb.AppendLine("\t\t\t}");
		sb.AppendLine();
		sb.AppendLine("\t\t\treturn output;");
		sb.AppendLine("\t\t}");

		sb.AppendLine("\t}");
		sb.AppendLine("}");

		string outDir = Path.Combine(targetOutputDir, nsDir);
		Directory.CreateDirectory(outDir);
		WriteFileIfChanged(Path.Combine(outDir, $"{className}.cs"), sb.ToString());
		filesWritten++;
	}
}

Console.WriteLine($"Generated {filesWritten} file(s) for {yamlFileName}.");
File.SetLastWriteTimeUtc(Path.Combine(targetOutputDir, $"{yamlFileName}PacketVersion.cs"), DateTime.UtcNow);

// ── File Utility Helper ─────────────────────────────────────────────────────
static void WriteFileIfChanged(string path, string newContent)
{
	if (File.Exists(path))
	{
		string existingContent = File.ReadAllText(path);
		if (existingContent == newContent)
			return;
	}

	Directory.CreateDirectory(Path.GetDirectoryName(path)!);
	File.WriteAllText(path, newContent, Encoding.UTF8);
}

// ── YAML Data Models ────────────────────────────────────────────────────────
public class PacketConfig
{
	public string Namespace { get; set; } = "";
	public string OpcodeEnum { get; set; } = "";
	public string OutputPath { get; set; } = "";
	public Dictionary<string, Dictionary<string, DirectionSpec>> Packets { get; set; } = new();
}

public class DirectionSpec
{
	public string? Prefix { get; set; }
	public string? Proto { get; set; }
}