using System;
using System.Collections.Generic;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;

if (args.Length == 0)
{
	Console.WriteLine("Usage: PacketGenerator <path-to-json>");
	return;
}

string jsonPath = Path.GetFullPath(args[0]);
if (!File.Exists(jsonPath))
{
	Console.WriteLine($"Error: File not found: {jsonPath}");
	return;
}

string jsonDir = Path.GetDirectoryName(jsonPath)!;
string jsonText = File.ReadAllText(jsonPath);
JsonNode root = JsonNode.Parse(jsonText)!;

string namespaceName = root["namespace"]!.GetValue<string>();
string opcodeEnum = root["opcodeEnum"]!.GetValue<string>();
string outputPath = root["outputPath"]!.GetValue<string>();
JsonArray packets = root["packets"]!.AsArray();

string targetOutputDir = Path.GetFullPath(Path.Combine(jsonDir, outputPath));
Directory.CreateDirectory(targetOutputDir);

// ── Revision Check ──────────────────────────────────────────────────────────
string jsonFileName = Path.GetFileNameWithoutExtension(jsonPath);
string revisionPath = Path.Combine(jsonDir, $"{jsonFileName}Version.json");

int revision = 0;
string storedHash = "";

if (File.Exists(revisionPath))
{
	var revRoot = JsonNode.Parse(File.ReadAllText(revisionPath))!;
	revision = revRoot["revision"]!.GetValue<int>();
	storedHash = revRoot["hash"]?.GetValue<string>() ?? "";
}

byte[] hashBytes = MD5.HashData(Encoding.UTF8.GetBytes(jsonText));
string currentHash = Convert.ToHexString(hashBytes).ToLowerInvariant();

if (currentHash != storedHash)
{
	revision++;
	string revisionJson = JsonSerializer.Serialize(new { revision, hash = currentHash }, new JsonSerializerOptions { WriteIndented = true });
	WriteFileIfChanged(revisionPath, revisionJson);
}

// ── Emit Revision File ───────────────────────────────────────────────────────
var revSb = new StringBuilder();
revSb.AppendLine("// <auto-generated>");
revSb.AppendLine($"//    Generated from {Path.GetFileName(jsonPath)} — do NOT edit manually.");
revSb.AppendLine("// </auto-generated>");
revSb.AppendLine($"namespace {namespaceName}");
revSb.AppendLine("{");
revSb.AppendLine($"\tpublic static class {jsonFileName}PacketVersion");
revSb.AppendLine("\t{");
revSb.AppendLine($"\t\tpublic const int Revision = {revision};");
revSb.AppendLine("\t}");
revSb.AppendLine("}");

WriteFileIfChanged(Path.Combine(targetOutputDir, $"{jsonFileName}PacketVersion.cs"), revSb.ToString());

// ── Generate Packets ────────────────────────────────────────────────────────
int filesWritten = 1;

foreach (JsonNode? pktNode in packets)
{
	string packetName = pktNode!["name"]!.GetValue<string>();
	string opcode = packetName.ToUpperInvariant();
	JsonArray dirs = pktNode["directions"]!.AsArray();

	foreach (JsonNode? dirNode in dirs)
	{
		string direction = dirNode!["direction"]!.GetValue<string>();
		string handlerName = $"{packetName}Handler";
		JsonArray fields = dirNode["fields"]!.AsArray();

		bool isC2S = direction == "C2S";
		string prefix = isC2S ? "REQ" : dirNode["prefix"]?.GetValue<string>()
			?? throw new InvalidOperationException($"S2C direction of '{packetName}' missing prefix.");

		string className = $"{prefix}_{packetName}";
		string nsDir = isC2S ? "C2S" : "S2C";
		string fullNs = $"{namespaceName}.{nsDir}";

		var fieldList = new List<(string csType, string name, string member, int? size, string? param)>();
		foreach (JsonNode? f in fields)
		{
			string ft = CsType(f!["type"]!.GetValue<string>());
			string fn = f["name"]!.GetValue<string>();
			int? fsz = f["size"]?.GetValue<int>();
			string? fp = f["param"] is not null ? FieldMember(f["param"]!.GetValue<string>()) : null;
			fieldList.Add((ft, fn, FieldMember(fn), fsz, fp));
		}

		string actionType = ActionType("ClientClass", fields);
		string ctorParams = string.Join(", ", fieldList.Select(f => $"{f.csType} {f.member[1..]}"));

		var sb = new StringBuilder();
		sb.AppendLine("// <auto-generated>");
		sb.AppendLine($"//    Generated from {Path.GetFileName(jsonPath)} — do NOT edit manually.");
		sb.AppendLine("// </auto-generated>");
		sb.AppendLine("#nullable enable");
		sb.AppendLine("using LibPegasus.Enums;");
		sb.AppendLine("using LibPegasus.Packets;");
		sb.AppendLine("using Nito.Collections;");
		sb.AppendLine("using System;");
		sb.AppendLine("using System.Collections.Generic;");
		sb.AppendLine();
		sb.AppendLine($"namespace {fullNs}");
		sb.AppendLine("{");
		sb.AppendLine($"\tpublic class {className}<ClientClass> : Packet<ClientClass>");
		sb.AppendLine("\t{");

		// Fields
		foreach (var f in fieldList)
			sb.AppendLine($"\t\tprivate {f.csType}{(f.csType is "byte[]" or "String" ? "?" : "")} {f.member};");
		sb.AppendLine();

		// Handler
		sb.AppendLine($"\t\tpublic static {actionType}? {handlerName};");
		sb.AppendLine();

		// Reader Ctor & ReadPayload
		sb.AppendLine($"\t\tpublic {className}(Queue<byte> data) : base((UInt16){opcodeEnum}.{opcode}, data) {{ }}");
		sb.AppendLine();
		sb.AppendLine("\t\tpublic override bool ReadPayload(Queue<Action<ClientClass>> actions)");
		sb.AppendLine("\t\t{");
		sb.AppendLine("\t\t\ttry");
		sb.AppendLine("\t\t\t{");
		foreach (var f in fieldList)
			sb.AppendLine($"\t\t\t\t{f.member} = {ReaderCall(f.csType, f.size, f.param)};");
		sb.AppendLine("\t\t\t}");
		sb.AppendLine("\t\t\tcatch (IndexOutOfRangeException) { return false; }");
		sb.AppendLine();
		sb.AppendLine($"\t\t\tif ({handlerName} == null)");
		sb.AppendLine(isC2S ? "\t\t\t\tthrow new InvalidOperationException(\"Handler not assigned\");" : "\t\t\t\treturn false;");
		sb.AppendLine();
		string invokeArgs = string.Join("", fieldList.Select(f => ", " + f.member));
		sb.AppendLine($"\t\t\tactions.Enqueue((x) => {handlerName}?.Invoke(x{invokeArgs}));");
		sb.AppendLine("\t\t\treturn true;");
		sb.AppendLine("\t\t}");
		sb.AppendLine();

		// Writer Ctor & WritePayload
		sb.AppendLine($"\t\tpublic {className}({ctorParams}) : base((UInt16){opcodeEnum}.{opcode})");
		sb.AppendLine("\t\t{");
		foreach (var f in fieldList)
			sb.AppendLine($"\t\t\t{f.member} = {f.member[1..]};");
		sb.AppendLine("\t\t}");
		sb.AppendLine();
		sb.AppendLine("\t\tpublic override void WritePayload(Deque<byte> data)");
		sb.AppendLine("\t\t{");
		foreach (var f in fieldList)
			sb.AppendLine($"\t\t\t{WriterCall(f.csType, f.member, f.size)};");
		sb.AppendLine("\t\t}");
		sb.AppendLine("\t}");
		sb.AppendLine("}");

		string outDir = Path.Combine(targetOutputDir, nsDir);
		Directory.CreateDirectory(outDir);
		WriteFileIfChanged(Path.Combine(outDir, $"{className}.cs"), sb.ToString());
		filesWritten++;
	}
}

Console.WriteLine($"Generated {filesWritten} file(s) for {jsonFileName}.");
File.SetLastWriteTimeUtc(Path.Combine(targetOutputDir, $"{jsonFileName}PacketVersion.cs"), DateTime.UtcNow);

// ── Local Helpers ────────────────────────────────────────────────────────────
static string CsType(string t) => t switch
{
	"uint32" or "UInt32" => "UInt32",
	"uint16" or "UInt16" => "UInt16",
	"byte[]" => "byte[]",
	"byte" => "Byte",
	"string" => "String",
	_ => t
};

static string ReaderCall(string csType, int? size, string? param) => csType switch
{
	"UInt32" => "PacketReader.ReadUInt32(_data)",
	"UInt16" => "PacketReader.ReadUInt16(_data)",
	"Byte" => "PacketReader.ReadByte(_data)",
	"byte[]" => size.HasValue ? $"PacketReader.ReadArray(_data, {size})" : "PacketReader.ReadArray(_data)",
	"String" => $"PacketReader.ReadString(_data, {param})",
	_ => $"PacketReader.Read{csType}(_data)"
};

static string WriterCall(string csType, string fieldName, int? size) => csType switch
{
	"UInt32" => $"PacketWriter.WriteUInt32(data, {fieldName})",
	"UInt16" => $"PacketWriter.WriteUInt16(data, {fieldName})",
	"Byte" => $"PacketWriter.WriteByte(data, {fieldName})",
	"byte[]" => $"PacketWriter.WriteArray(data, {fieldName})",
	"String" => $"PacketWriter.WriteString(data, {fieldName})",
	_ => $"PacketWriter.Write{csType}(data, {fieldName})"
};

static string ActionType(string clientClass, JsonArray fields)
{
	var parts = new List<string> { clientClass };
	foreach (var f in fields)
		parts.Add(CsType(f!["type"]!.GetValue<string>()));
	return $"Action<{string.Join(", ", parts)}>";
}

static string FieldMember(string name) => "_" + char.ToLower(name[0]) + name[1..];

static void WriteFileIfChanged(string path, string newContent)
{
	if (File.Exists(path))
	{
		string existingContent = File.ReadAllText(path);
		if (existingContent == newContent)
			return; // Skip writing to preserve the file timestamp!
	}

	Directory.CreateDirectory(Path.GetDirectoryName(path)!);
	File.WriteAllText(path, newContent, Encoding.UTF8);
}