// <auto-generated>
//    Generated from Login.yaml — do NOT edit manually.
// </auto-generated>
#nullable enable
using Google.Protobuf;
using LibPegasus.Enums;
using LibPegasus.Packets;
using Nito.Collections;
using System;
using System.Collections.Generic;

namespace LibPegasus.Packets.Login.S2C
{
	public class NFY_ServerState<ClientClass> : Packet<ClientClass>
	{
		public LibPegasus.Protobuf.Login.ServerStateNfy Body { get; private set; }

		public static Action<ClientClass, LibPegasus.Protobuf.Login.ServerStateNfy>? ServerStateHandler;

		public NFY_ServerState(Queue<byte> data) : base((UInt16)OpcodeLogin.SERVERSTATE, data)
		{
			Body = new LibPegasus.Protobuf.Login.ServerStateNfy();
		}

		public NFY_ServerState(LibPegasus.Protobuf.Login.ServerStateNfy body) : base((UInt16)OpcodeLogin.SERVERSTATE)
		{
			Body = body ?? throw new ArgumentNullException(nameof(body));
		}

		public override bool ReadPayload(Queue<Action<ClientClass>> actions)
		{
			try
			{
				byte[] payloadBytes = PacketReader.ReadArray(_data);
				Body = LibPegasus.Protobuf.Login.ServerStateNfy.Parser.ParseFrom(payloadBytes);
			}
			catch (Exception)
			{
				return false;
			}

			if (ServerStateHandler == null)
				return false;

			actions.Enqueue((client) => ServerStateHandler?.Invoke(client, Body));
			return true;
		}

		public override void WritePayload(Deque<byte> data)
		{
			byte[] payloadBytes = Body.ToByteArray();
			PacketWriter.WriteArray(data, payloadBytes);
		}
	}
}
