// <auto-generated>
//   Generated by LoginPacketGenerator.tt from Login.json — do NOT edit manually.
// </auto-generated>
#nullable enable
using LibPegasus.Enums;
using LibPegasus.Packets;
using Nito.Collections;

namespace LibPegasus.Packets.Login.S2C
{
	public class RSP_CheckVersion<ClientClass> : Packet<ClientClass>
	{
		// ── Fields ──────────────────────────────────────────────────────────
		private Byte _versionOk;

		// ── Handler ─────────────────────────────────────────────────────────
		public static Action<ClientClass, Byte>? CheckVersionHandler;

		// ── Deserialising constructor (reads from wire) ──────────────────────
		public RSP_CheckVersion(Queue<byte> data)
			: base((UInt16)OpcodeLogin.CHECKVERSION, data) { }

		public override bool ReadPayload(Queue<Action<ClientClass>> actions)
		{
			try
			{
				_versionOk = PacketReader.ReadByte(_data);
			}
			catch (IndexOutOfRangeException)
			{
				return false;
			}

			if (CheckVersionHandler == null)
				return false;

			actions.Enqueue((x) => CheckVersionHandler?.Invoke(x, _versionOk));
			return true;
		}

		// ── Serialising constructor (writes to wire) ─────────────────────────
		public RSP_CheckVersion(Byte versionOk)
			: base((UInt16)OpcodeLogin.CHECKVERSION)
		{
			_versionOk = versionOk;
		}

		public override void WritePayload(Deque<byte> data)
		{
			PacketWriter.WriteByte(data, _versionOk);
		}
	}
}
