// <auto-generated>
//    Generated from Login.yaml — do NOT edit manually.
// </auto-generated>
#nullable enable
using Google.Protobuf;
using LibPegasus.Enums;
using LibPegasus.Packets;
using Nito.Collections;
using System;
using System.Collections.Generic;

namespace LibPegasus.Packets.Login.S2C
{
	public class RSP_CheckVersion<ClientClass> : Packet<ClientClass>
	{
		public LibPegasus.Protobuf.Login.CheckVersionRsp Body { get; private set; }

		public static Action<ClientClass, LibPegasus.Protobuf.Login.CheckVersionRsp>? CheckVersionHandler;

		public RSP_CheckVersion(Queue<byte> data) : base((UInt16)OpcodeLogin.CHECKVERSION, data)
		{
			Body = new LibPegasus.Protobuf.Login.CheckVersionRsp();
		}

		public RSP_CheckVersion(LibPegasus.Protobuf.Login.CheckVersionRsp body) : base((UInt16)OpcodeLogin.CHECKVERSION)
		{
			Body = body ?? throw new ArgumentNullException(nameof(body));
		}

		public override bool ReadPayload(Queue<Action<ClientClass>> actions)
		{
			try
			{
				byte[] payloadBytes = PacketReader.ReadArray(_data);
				Body = LibPegasus.Protobuf.Login.CheckVersionRsp.Parser.ParseFrom(payloadBytes);
			}
			catch (Exception)
			{
				return false;
			}

			if (CheckVersionHandler == null)
				return false;

			actions.Enqueue((client) => CheckVersionHandler?.Invoke(client, Body));
			return true;
		}

		public override void WritePayload(Deque<byte> data)
		{
			byte[] payloadBytes = Body.ToByteArray();
			PacketWriter.WriteArray(data, payloadBytes);
		}
	}
}
