// <auto-generated>
//   Generated by LoginPacketGenerator.tt from Login.json — do NOT edit manually.
// </auto-generated>
#nullable enable
using LibPegasus.Enums;
using LibPegasus.Packets;
using Nito.Collections;

namespace LibPegasus.Packets.Login.S2C
{
	public class RSP_AuthAccount<ClientClass> : Packet<ClientClass>
	{
		// ── Fields ──────────────────────────────────────────────────────────
		private byte[]? _authAccountReply;

		// ── Handler ─────────────────────────────────────────────────────────
		public static Action<ClientClass, byte[]>? OnAuthAccountHandler;

		// ── Deserialising constructor (reads from wire) ──────────────────────
		public RSP_AuthAccount(Queue<byte> data)
			: base((UInt16)OpcodeLogin.AUTHACCOUNT, data) { }

		public override bool ReadPayload(Queue<Action<ClientClass>> actions)
		{
			try
			{
				_authAccountReply = PacketReader.ReadArray(_data);
			}
			catch (IndexOutOfRangeException)
			{
				return false;
			}

			if (OnAuthAccountHandler == null)
				return false;

			actions.Enqueue((x) => OnAuthAccountHandler?.Invoke(x, _authAccountReply));
			return true;
		}

		// ── Serialising constructor (writes to wire) ─────────────────────────
		public RSP_AuthAccount(byte[] authAccountReply)
			: base((UInt16)OpcodeLogin.AUTHACCOUNT)
		{
			_authAccountReply = authAccountReply;
		}

		public override void WritePayload(Deque<byte> data)
		{
			PacketWriter.WriteArray(data, _authAccountReply);
		}
	}
}
