// <auto-generated>
//    Generated from Login.yaml — do NOT edit manually.
// </auto-generated>
#nullable enable
using Google.Protobuf;
using LibPegasus.Enums;
using LibPegasus.Packets;
using Nito.Collections;
using System;
using System.Collections.Generic;

namespace LibPegasus.Packets.Login.S2C
{
	public class RSP_AuthAccount<ClientClass> : Packet<ClientClass>
	{
		public LibPegasus.Protobuf.Login.AuthAccountRsp Body { get; private set; }

		public static Action<ClientClass, LibPegasus.Protobuf.Login.AuthAccountRsp>? AuthAccountHandler;

		public RSP_AuthAccount(Queue<byte> data) : base((UInt16)OpcodeLogin.AUTHACCOUNT, data)
		{
			Body = new LibPegasus.Protobuf.Login.AuthAccountRsp();
		}

		public RSP_AuthAccount(LibPegasus.Protobuf.Login.AuthAccountRsp body) : base((UInt16)OpcodeLogin.AUTHACCOUNT)
		{
			Body = body ?? throw new ArgumentNullException(nameof(body));
		}

		public override bool ReadPayload(Queue<Action<ClientClass>> actions)
		{
			try
			{
				byte[] payloadBytes = PacketReader.ReadArray(_data);
				Body = LibPegasus.Protobuf.Login.AuthAccountRsp.Parser.ParseFrom(payloadBytes);
			}
			catch (Exception)
			{
				return false;
			}

			if (AuthAccountHandler == null)
				return false;

			actions.Enqueue((client) => AuthAccountHandler?.Invoke(client, Body));
			return true;
		}

		public override void WritePayload(Deque<byte> data)
		{
			byte[] payloadBytes = Body.ToByteArray();
			PacketWriter.WriteArray(data, payloadBytes);
		}
	}
}
