// <auto-generated>
//    Generated from Login.yaml — do NOT edit manually.
// </auto-generated>
#nullable enable
using Google.Protobuf;
using LibPegasus.Enums;
using LibPegasus.Packets;
using Nito.Collections;
using System;
using System.Buffers;
using System.Collections.Generic;

namespace LibPegasus.Packets.Login.S2C
{
	public class RSP_VerifyLinks<ClientClass> : Packet<ClientClass>
	{
		public LibPegasus.Protobuf.Login.VerifyLinksRsp Body { get; private set; }

		public static Action<ClientClass, LibPegasus.Protobuf.Login.VerifyLinksRsp>? VerifyLinksHandler;

		public RSP_VerifyLinks(Queue<byte> data) : base((UInt16)OpcodeLogin.VERIFYLINKS, data)
		{
			Body = new LibPegasus.Protobuf.Login.VerifyLinksRsp();
		}

		public RSP_VerifyLinks(LibPegasus.Protobuf.Login.VerifyLinksRsp body) : base((UInt16)OpcodeLogin.VERIFYLINKS)
		{
			Body = body ?? throw new ArgumentNullException(nameof(body));
		}

		public override bool ReadPayload(Queue<Action<ClientClass>> actions)
		{
			int payloadSize = _data.Count;
			if (payloadSize == 0) return false;

			byte[] buffer = ArrayPool<byte>.Shared.Rent(payloadSize);
			try
			{
				Span<byte> span = buffer.AsSpan(0, payloadSize);
				PacketReader.ReadSpan(_data, span);
				Body = LibPegasus.Protobuf.Login.VerifyLinksRsp.Parser.ParseFrom(span);
			}
			catch (InvalidProtocolBufferException)
			{
				return false;
			}
			finally
			{
				ArrayPool<byte>.Shared.Return(buffer, clearArray: false);
			}

			if (VerifyLinksHandler == null)
				return false;

			actions.Enqueue((client) => VerifyLinksHandler?.Invoke(client, Body));
			return true;
		}

		public override byte[] WritePayload()
		{
			if (Body == null)
				return new byte[HEADER_SIZE];

			int size = Body.CalculateSize();
			byte[] output = new byte[HEADER_SIZE + size];

			if (size > 0)
			{
				Span<byte> span = output.AsSpan(HEADER_SIZE, size);
				Body.WriteTo(span);
			}

			return output;
		}
	}
}
