// <auto-generated>
//    Generated from Login.json — do NOT edit manually.
// </auto-generated>
#nullable enable
using LibPegasus.Enums;
using LibPegasus.Packets;
using Nito.Collections;
using System;
using System.Collections.Generic;

namespace LibPegasus.Packets.Login.S2C
{
	public class RSP_ConnectServer<ClientClass> : Packet<ClientClass>
	{
		private UInt32 _authKey;
		private UInt16 _userIdx;
		private byte[]? _serverNonce;
		private byte[]? _publicServerKey;

		public static Action<ClientClass, UInt32, UInt16, byte[], byte[]>? ConnectServerHandler;

		public RSP_ConnectServer(Queue<byte> data) : base((UInt16)OpcodeLogin.CONNECTSERVER, data) { }

		public override bool ReadPayload(Queue<Action<ClientClass>> actions)
		{
			try
			{
				_authKey = PacketReader.ReadUInt32(_data);
				_userIdx = PacketReader.ReadUInt16(_data);
				_serverNonce = PacketReader.ReadArray(_data, 8);
				_publicServerKey = PacketReader.ReadArray(_data, 32);
			}
			catch (IndexOutOfRangeException) { return false; }

			if (ConnectServerHandler == null)
				return false;

			actions.Enqueue((x) => ConnectServerHandler?.Invoke(x, _authKey, _userIdx, _serverNonce, _publicServerKey));
			return true;
		}

		public RSP_ConnectServer(UInt32 authKey, UInt16 userIdx, byte[] serverNonce, byte[] publicServerKey) : base((UInt16)OpcodeLogin.CONNECTSERVER)
		{
			_authKey = authKey;
			_userIdx = userIdx;
			_serverNonce = serverNonce;
			_publicServerKey = publicServerKey;
		}

		public override void WritePayload(Deque<byte> data)
		{
			PacketWriter.WriteUInt32(data, _authKey);
			PacketWriter.WriteUInt16(data, _userIdx);
			PacketWriter.WriteArray(data, _serverNonce);
			PacketWriter.WriteArray(data, _publicServerKey);
		}
	}
}
