// <auto-generated>
//    Generated from World.json — do NOT edit manually.
// </auto-generated>
#nullable enable
using LibPegasus.Enums;
using LibPegasus.Packets;
using Nito.Collections;
using System;
using System.Collections.Generic;

namespace LibPegasus.Packets.World.S2C
{
	public class RSP_DummyPacket<ClientClass> : Packet<ClientClass>
	{
		private byte[]? _response;

		public static Action<ClientClass, byte[]>? DummyPacketHandler;

		public RSP_DummyPacket(Queue<byte> data) : base((UInt16)OpcodeWorld.DUMMYPACKET, data) { }

		public override bool ReadPayload(Queue<Action<ClientClass>> actions)
		{
			try
			{
				_response = PacketReader.ReadArray(_data);
			}
			catch (IndexOutOfRangeException) { return false; }

			if (DummyPacketHandler == null)
				return false;

			actions.Enqueue((x) => DummyPacketHandler?.Invoke(x, _response));
			return true;
		}

		public RSP_DummyPacket(byte[] response) : base((UInt16)OpcodeWorld.DUMMYPACKET)
		{
			_response = response;
		}

		public override void WritePayload(Deque<byte> data)
		{
			PacketWriter.WriteArray(data, _response);
		}
	}
}
