// <auto-generated>
//    Generated from World.yaml — do NOT edit manually.
// </auto-generated>
#nullable enable
using Google.Protobuf;
using LibPegasus.Enums;
using LibPegasus.Packets;
using Nito.Collections;
using System;
using System.Buffers;
using System.Collections.Generic;

namespace LibPegasus.Packets.World.S2C
{
	public class RSP_ConnectServer<ClientClass> : Packet<ClientClass>
	{
		public LibPegasus.Protobuf.World.ConnectServerRsp Body { get; private set; }

		public static Action<ClientClass, LibPegasus.Protobuf.World.ConnectServerRsp>? ConnectServerHandler;

		public RSP_ConnectServer(byte[] data) : base((UInt16)OpcodeWorld.CONNECTSERVER, data)
		{
			Body = new LibPegasus.Protobuf.World.ConnectServerRsp();
		}

		public RSP_ConnectServer(LibPegasus.Protobuf.World.ConnectServerRsp body) : base((UInt16)OpcodeWorld.CONNECTSERVER)
		{
			Body = body ?? throw new ArgumentNullException(nameof(body));
		}

		public override bool ReadPayload(Queue<Action<ClientClass>> actions)
		{
			if (_data == null)
				throw new NullReferenceException("null _data");

			if (_data.Length < HEADER_SIZE)
				return false;

			ReadOnlySpan<byte> span = _data.AsSpan(HEADER_SIZE);
			if (span.IsEmpty)
				return true;

			try
			{
				Body = LibPegasus.Protobuf.World.ConnectServerRsp.Parser.ParseFrom(span);
			}
			catch (InvalidProtocolBufferException ex)
			{
				Serilog.Log.Debug($"{ex}");
				return false;
			}

			if (ConnectServerHandler == null)
				return false;

			actions.Enqueue((client) => ConnectServerHandler?.Invoke(client, Body));
			return true;
		}

		public override byte[] WritePayload()
		{
			if (Body == null)
				return new byte[HEADER_SIZE];

			int size = Body.CalculateSize();
			byte[] output = new byte[HEADER_SIZE + size];

			if (size > 0)
			{
				Span<byte> span = output.AsSpan(HEADER_SIZE, size);
				Body.WriteTo(span);
			}

			return output;
		}
	}
}
