// <auto-generated>
//   Generated by LoginPacketGenerator.tt from Login.json — do NOT edit manually.
// </auto-generated>
#nullable enable
using LibPegasus.Enums;
using LibPegasus.Packets;
using Nito.Collections;

namespace LibPegasus.Packets.Login.C2S
{
	public class REQ_ConnectServer<ClientClass> : Packet<ClientClass>
	{
		// ── Fields ──────────────────────────────────────────────────────────
		private byte[]? _clientNonce;
		private byte[]? _clientPublicKey;

		// ── Handler ─────────────────────────────────────────────────────────
		public static Action<ClientClass, byte[], byte[]>? ConnectServerHandler;

		// ── Deserialising constructor (reads from wire) ──────────────────────
		public REQ_ConnectServer(Queue<byte> data)
			: base((UInt16)OpcodeLogin.CONNECTSERVER, data) { }

		public override bool ReadPayload(Queue<Action<ClientClass>> actions)
		{
			try
			{
				_clientNonce = PacketReader.ReadArray(_data, 8);
				_clientPublicKey = PacketReader.ReadArray(_data, 32);
			}
			catch (IndexOutOfRangeException)
			{
				return false;
			}

			if (ConnectServerHandler == null)
				throw new InvalidOperationException("Handler not assigned");

			actions.Enqueue((x) => ConnectServerHandler?.Invoke(x, _clientNonce, _clientPublicKey));
			return true;
		}

		// ── Serialising constructor (writes to wire) ─────────────────────────
		public REQ_ConnectServer(byte[] clientNonce, byte[] clientPublicKey)
			: base((UInt16)OpcodeLogin.CONNECTSERVER)
		{
			_clientNonce = clientNonce;
			_clientPublicKey = clientPublicKey;
		}

		public override void WritePayload(Deque<byte> data)
		{
			PacketWriter.WriteArray(data, _clientNonce); // 8 byte
			PacketWriter.WriteArray(data, _clientPublicKey); // 32 byte
		}
	}
}
