// <auto-generated>
//    Generated from Login.yaml — do NOT edit manually.
// </auto-generated>
#nullable enable
using Google.Protobuf;
using LibPegasus.Enums;
using LibPegasus.Packets;
using Nito.Collections;
using System;
using System.Buffers;
using System.Collections.Generic;

namespace LibPegasus.Packets.Login.C2S
{
	public class REQ_VerifyLinks<ClientClass> : Packet<ClientClass>
	{
		public LibPegasus.Protobuf.Login.VerifyLinksReq Body { get; private set; }

		public static Action<ClientClass, LibPegasus.Protobuf.Login.VerifyLinksReq>? VerifyLinksHandler;

		public REQ_VerifyLinks(Queue<byte> data) : base((UInt16)OpcodeLogin.VERIFYLINKS, data)
		{
			Body = new LibPegasus.Protobuf.Login.VerifyLinksReq();
		}

		public REQ_VerifyLinks(LibPegasus.Protobuf.Login.VerifyLinksReq body) : base((UInt16)OpcodeLogin.VERIFYLINKS)
		{
			Body = body ?? throw new ArgumentNullException(nameof(body));
		}

		public override bool ReadPayload(Queue<Action<ClientClass>> actions)
		{
			int payloadSize = _data.Count;
			if (payloadSize == 0) return false;

			byte[] buffer = ArrayPool<byte>.Shared.Rent(payloadSize);
			try
			{
				Span<byte> span = buffer.AsSpan(0, payloadSize);
				PacketReader.ReadSpan(_data, span);
				Body = LibPegasus.Protobuf.Login.VerifyLinksReq.Parser.ParseFrom(span);
			}
			catch (InvalidProtocolBufferException)
			{
				return false;
			}
			finally
			{
				ArrayPool<byte>.Shared.Return(buffer, clearArray: false);
			}

			if (VerifyLinksHandler == null)
				throw new InvalidOperationException("Handler not assigned");

			actions.Enqueue((client) => VerifyLinksHandler?.Invoke(client, Body));
			return true;
		}

		public override int WritePayload(Deque<byte> data)
		{
			if (Body == null) return 0;

			int size = Body.CalculateSize();
			if (size == 0) return 0;

			byte[] buffer = ArrayPool<byte>.Shared.Rent(size);
			try
			{
				Span<byte> span = buffer.AsSpan(0, size);
				Body.WriteTo(span);
				PacketWriter.WriteArray(data, span);
			}
			finally
			{
				ArrayPool<byte>.Shared.Return(buffer, clearArray: false);
			}
			return size;
		}
	}
}
