// <auto-generated>
//    Generated from Login.yaml — do NOT edit manually.
// </auto-generated>
#nullable enable
using Google.Protobuf;
using LibPegasus.Enums;
using LibPegasus.Packets;
using Nito.Collections;
using System;
using System.Buffers;
using System.Collections.Generic;

namespace LibPegasus.Packets.Login.C2S
{
	public class REQ_ConnectServer<ClientClass> : Packet<ClientClass>
	{
		public LibPegasus.Protobuf.Login.ConnectServerReq Body { get; private set; }

		public static Action<ClientClass, LibPegasus.Protobuf.Login.ConnectServerReq>? ConnectServerHandler;

		public REQ_ConnectServer(Queue<byte> data) : base((UInt16)OpcodeLogin.CONNECTSERVER, data)
		{
			Body = new LibPegasus.Protobuf.Login.ConnectServerReq();
		}

		public REQ_ConnectServer(LibPegasus.Protobuf.Login.ConnectServerReq body) : base((UInt16)OpcodeLogin.CONNECTSERVER)
		{
			Body = body ?? throw new ArgumentNullException(nameof(body));
		}

		public override bool ReadPayload(Queue<Action<ClientClass>> actions)
		{
			int payloadSize = _data.Count;
			if (payloadSize == 0) return false;

			byte[] buffer = ArrayPool<byte>.Shared.Rent(payloadSize);
			try
			{
				Span<byte> span = buffer.AsSpan(0, payloadSize);
				PacketReader.ReadSpan(_data, span);
				Body = LibPegasus.Protobuf.Login.ConnectServerReq.Parser.ParseFrom(span);
			}
			catch (InvalidProtocolBufferException)
			{
				return false;
			}
			finally
			{
				ArrayPool<byte>.Shared.Return(buffer, clearArray: false);
			}

			if (ConnectServerHandler == null)
				throw new InvalidOperationException("Handler not assigned");

			actions.Enqueue((client) => ConnectServerHandler?.Invoke(client, Body));
			return true;
		}

		public override byte[] WritePayload()
		{
			if (Body == null)
				return new byte[HEADER_SIZE];

			int size = Body.CalculateSize();
			byte[] output = new byte[HEADER_SIZE + size];

			if (size > 0)
			{
				Span<byte> span = output.AsSpan(HEADER_SIZE, size);
				Body.WriteTo(span);
			}

			return output;
		}
	}
}
