// <auto-generated>
//    Generated from Login.json — do NOT edit manually.
// </auto-generated>
#nullable enable
using LibPegasus.Enums;
using LibPegasus.Packets;
using Nito.Collections;
using System;
using System.Collections.Generic;

namespace LibPegasus.Packets.Login.C2S
{
	public class REQ_ConnectServer<ClientClass> : Packet<ClientClass>
	{
		private byte[]? _clientNonce;
		private byte[]? _clientPublicKey;

		public static Action<ClientClass, byte[], byte[]>? ConnectServerHandler;

		public REQ_ConnectServer(Queue<byte> data) : base((UInt16)OpcodeLogin.CONNECTSERVER, data) { }

		public override bool ReadPayload(Queue<Action<ClientClass>> actions)
		{
			try
			{
				_clientNonce = PacketReader.ReadArray(_data, 8);
				_clientPublicKey = PacketReader.ReadArray(_data, 32);
			}
			catch (IndexOutOfRangeException) { return false; }

			if (ConnectServerHandler == null)
				throw new InvalidOperationException("Handler not assigned");

			actions.Enqueue((x) => ConnectServerHandler?.Invoke(x, _clientNonce, _clientPublicKey));
			return true;
		}

		public REQ_ConnectServer(byte[] clientNonce, byte[] clientPublicKey) : base((UInt16)OpcodeLogin.CONNECTSERVER)
		{
			_clientNonce = clientNonce;
			_clientPublicKey = clientPublicKey;
		}

		public override void WritePayload(Deque<byte> data)
		{
			PacketWriter.WriteArray(data, _clientNonce);
			PacketWriter.WriteArray(data, _clientPublicKey);
		}
	}
}
