// <auto-generated>
//    Generated from Login.json — do NOT edit manually.
// </auto-generated>
#nullable enable
using LibPegasus.Enums;
using LibPegasus.Packets;
using Nito.Collections;
using System;
using System.Collections.Generic;

namespace LibPegasus.Packets.Login.C2S
{
	public class REQ_CheckVersion<ClientClass> : Packet<ClientClass>
	{
		private UInt32 _clientVersion;

		public static Action<ClientClass, UInt32>? CheckVersionHandler;

		public REQ_CheckVersion(Queue<byte> data) : base((UInt16)OpcodeLogin.CHECKVERSION, data) { }

		public override bool ReadPayload(Queue<Action<ClientClass>> actions)
		{
			try
			{
				_clientVersion = PacketReader.ReadUInt32(_data);
			}
			catch (IndexOutOfRangeException) { return false; }

			if (CheckVersionHandler == null)
				throw new InvalidOperationException("Handler not assigned");

			actions.Enqueue((x) => CheckVersionHandler?.Invoke(x, _clientVersion));
			return true;
		}

		public REQ_CheckVersion(UInt32 clientVersion) : base((UInt16)OpcodeLogin.CHECKVERSION)
		{
			_clientVersion = clientVersion;
		}

		public override void WritePayload(Deque<byte> data)
		{
			PacketWriter.WriteUInt32(data, _clientVersion);
		}
	}
}
