// <auto-generated>
//   Generated by LoginPacketGenerator.tt from Login.json — do NOT edit manually.
// </auto-generated>
#nullable enable
using LibPegasus.Enums;
using LibPegasus.Packets;
using Nito.Collections;

namespace LibPegasus.Packets.Login.C2S
{
	public class REQ_CheckVersion<ClientClass> : Packet<ClientClass>
	{
		// ── Fields ──────────────────────────────────────────────────────────
		private UInt32 _clientVersion;

		// ── Handler ─────────────────────────────────────────────────────────
		public static Action<ClientClass, UInt32>? OnCheckVersionHandler;

		// ── Deserialising constructor (reads from wire) ──────────────────────
		public REQ_CheckVersion(Queue<byte> data)
			: base((UInt16)OpcodeLogin.CHECKVERSION, data) { }

		public override bool ReadPayload(Queue<Action<ClientClass>> actions)
		{
			try
			{
				_clientVersion = PacketReader.ReadUInt32(_data);
			}
			catch (IndexOutOfRangeException)
			{
				return false;
			}

			if (OnCheckVersionHandler == null)
				throw new InvalidOperationException("Handler not assigned");

			actions.Enqueue((x) => OnCheckVersionHandler?.Invoke(x, _clientVersion));
			return true;
		}

		// ── Serialising constructor (writes to wire) ─────────────────────────
		public REQ_CheckVersion(UInt32 clientVersion)
			: base((UInt16)OpcodeLogin.CHECKVERSION)
		{
			_clientVersion = clientVersion;
		}

		public override void WritePayload(Deque<byte> data)
		{
			PacketWriter.WriteUInt32(data, _clientVersion);
		}
	}
}
