// <auto-generated>
//   Generated by LoginPacketGenerator.tt from Login.json — do NOT edit manually.
// </auto-generated>
#nullable enable
using LibPegasus.Enums;
using LibPegasus.Packets;
using Nito.Collections;

namespace LibPegasus.Packets.Login.C2S
{
	public class REQ_AuthAccount<ClientClass> : Packet<ClientClass>
	{
		// ── Fields ──────────────────────────────────────────────────────────
		private Byte _usernameLen;
		private String? _username;
		private Byte _passwordLen;
		private String? _password;

		// ── Handler ─────────────────────────────────────────────────────────
		public static Action<ClientClass, Byte, String, Byte, String>? OnAuthAccountHandler;

		// ── Deserialising constructor (reads from wire) ──────────────────────
		public REQ_AuthAccount(Queue<byte> data)
			: base((UInt16)OpcodeLogin.AUTHACCOUNT, data) { }

		public override bool ReadPayload(Queue<Action<ClientClass>> actions)
		{
			try
			{
				_usernameLen = PacketReader.ReadByte(_data);
				_username = PacketReader.ReadString(_data, _usernameLen);
				_passwordLen = PacketReader.ReadByte(_data);
				_password = PacketReader.ReadString(_data, _passwordLen);
			}
			catch (IndexOutOfRangeException)
			{
				return false;
			}

			if (OnAuthAccountHandler == null)
				throw new InvalidOperationException("Handler not assigned");

			actions.Enqueue((x) => OnAuthAccountHandler?.Invoke(x, _usernameLen, _username, _passwordLen, _password));
			return true;
		}

		// ── Serialising constructor (writes to wire) ─────────────────────────
		public REQ_AuthAccount(Byte usernameLen, String username, Byte passwordLen, String password)
			: base((UInt16)OpcodeLogin.AUTHACCOUNT)
		{
			_usernameLen = usernameLen;
			_username = username;
			_passwordLen = passwordLen;
			_password = password;
		}

		public override void WritePayload(Deque<byte> data)
		{
			PacketWriter.WriteByte(data, _usernameLen);
			PacketWriter.WriteString(data, _username);
			PacketWriter.WriteByte(data, _passwordLen);
			PacketWriter.WriteString(data, _password);
		}
	}
}
