// <auto-generated>
//   Generated by Packets.tt — do NOT edit manually.
// </auto-generated>
namespace LibPegasus.Packets.Login
{
	public static class LoginPacketVersion
	{
		public const int Revision = 2;
	}
}
