// <auto-generated>
//    Generated from Login.json — do NOT edit manually.
// </auto-generated>
namespace LibPegasus.Packets.Login
{
	public static class LoginPacketVersion
	{
		public const int Revision = 1;
	}
}
